version: '2'

checks:
  method-lines:
    enabled: false
  file-lines:
    enabled: true
    config:
      threshold: 400
  method-complexity:
    enabled: true
    config:
      threshold: 8

plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
    exclude_patterns:
      - '**/*.md'
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70
    exclude_patterns:
      - '**/__test__/'
      - '**/*.test.ts'
      - '**/*.spec.ts'

exclude_patterns:
  - '.idea/'
  - '.husky/'
  - '.lighthouse/'
  - 'coverage/'
  - 'dist/'
  - 'charts/'
  - 'preview/'
  - '**/node_modules/'
  - '.babelrc.js'
  - '.importsortrc.js'
  - '.lintstagedrc.js'
  - 'gatsby-node.js'
  - 'index.js'
  - 'jest.config.js'
  - 'LICENSE'
  - 'OWNERS'
  - 'OWNERS_ALIASES'
  - 'loadershim.js'
  - '**/__test__/'
  - '**/tests/'
  - '**/vendor/'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.types.ts'
  - '**/*.d.ts'
